frontend:
  - any:
      - 'src/**/*'
      - 'build/**/*'
      - 'config/**/*'
      - 'static/**/*'
      - 'test/**/*'
      - 'package.json'
      - 'eslint.config.js'

ci:
  - any:
      - '.github/workflows/**/*'
      - '.github/actions/**/*'
      - '.pre-commit-config.yaml'

documentation:
  - any:
      - '*.md'
      - 'docs/**/*'
      - 'static/llms.txt'
