[default.extend-words]
genzouw = "genzouw"
hyakuninissyu = "hyakuninissyu"
repomix = "repomix"
zizmor = "zizmor"
qodo = "qodo"
coderabbit = "coderabbit"
styl = "styl"
llms = "llms"
tfstate = "tfstate"
