[default.extend-words]
genzouw = "genzouw"
hyakuninissyu = "hyakuninissyu"
repomix = "repomix"
zizmor = "zizmor"
qodo = "Qodo"
coderabbit = "coderabbit"
codacy = "codacy"
styl = "styl"
llms = "llms"
tfstate = "tfstate"
