name: Scorecard supply-chain security
# オープンソースリポジトリのセキュリティと品質のベストプラクティスを自動評価する OSSF Scorecard
# 導入にあたり、GitHubリポジトリの設定で Code Scanning (Advanced Security) が有効になっている必要があります。

on:
  branch_protection_rule:
  schedule:
    - cron: '30 2 * * 0'
  push:
    branches: ['main']

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read

    steps:
      - name: 'リポジトリのチェックアウト'
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: 'Scorecard による分析の実行'
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: 'アーティファクトのアップロード'
        uses: actions/upload-artifact@v7
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      - name: 'GitHub Code Scanning へのアップロード'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
